version: '3'
services:
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: 123
        #    MYSQL_USER: bluespice
        #    MYSQL_PASSWORT: 123
        networks:
            - dbnet
        #test only
        ports:
            - "3306:3306"
    web:
        #build: ./apachephp
        image: mycent
        ports:
            - "80:80"
        networks: 
            - dbnet
            - appnet
        #volumes:
        #- .:/code
        #- logvolume01:/var/log
        #links:
        #- redis
    pvisual:
        image: pvisual
        ports:
            - "8000:8000"
        networks: 
            - appnet
    elastic:
        image: elastic
        ports:
            - "9200:9200"
            - "9300:9300"
        environment: 
            - discovery.type=single-node
        networks: 
            - appnet
networks:
    dbnet: {}
    appnet: {} 
volumes:
    logvolume01: {}