version: '3'
services:
  web:
    #build: ./apachephp
    image: mycent
    ports:
        - "8080:80"
    networks: 
        - dbnet
    #volumes:
    #- .:/code
    #- logvolume01:/var/log
    #links:
    #- redis
  db:
    image: mariadb
    environment: 
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_USER: bluespice
        MYSQL_PASSWORT: 123
    networks:
        - dbnet
networks:
    dbnet: {} 
volumes:
    logvolume01: {}