apiVersion: batch/v2alpha1
kind: CronJob
metadata: 
  name: dbbackup
spec:
  schedule: "30 16 * * *"  
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjob-dbbackup"
        spec:
          volumes: 
          - name: dbbackup
            persistentVolumeClaim:
              claimName: pv002-backup
          containers:
          - name: dbbackup
            image: "registry.dev.paas.verwalt-berlin.de/openshift/mariadb-101-rhel7:latest"
#            pullSecret:
#              name: pid-0047-garage-mediawiki-dev-secret-pull
            volumeMounts:
            - name: dbbackup
              mountPath: /backup
            command:
              - 'bash'
              - '-eo'
              - 'pipefail'
              - '-c' 
              - > 
                mkdir -p /backup/backup;
                mysqldump --skip-lock-tables -h mediawikidb -u root --password="mediawikiuser1" --all-databases > /backup/backup/all-`date +%Y-%m-%d_%H%M%S`.sql;
          restartPolicy: Never 